---
# OMV 設定適用ロール: 共有フォルダとSMB共有の作成/更新

- name: Enable SMB service
  import_tasks: smb_service.yml

- name: Create shared folders
  import_tasks: sharedfolders.yml

- name: Configure SMB shares
  import_tasks: smb_shares.yml

- name: Deploy SMB configuration via omv-salt
  command: omv-salt deploy run samba
  register: omv_salt_samba
  changed_when: false
  failed_when: false
