---
# SMB 共有（Smb.setShare）を作成/更新する。

- name: Read current SMB shares
  command: omv-confdbadm read conf.service.smb.share
  register: smb_share_raw
  changed_when: false
  failed_when: false

- name: Parse SMB shares
  set_fact:
    smb_share_parsed: "{{ (smb_share_raw.stdout | default('[]')) | from_json | default([], true) }}"

- name: Normalize SMB share list
  set_fact:
    smb_share_items: "{{ (smb_share_parsed.config if (smb_share_parsed is mapping and 'config' in smb_share_parsed) else smb_share_parsed) | list }}"

- name: Lookup existing SMB shares by name
  set_fact:
    smb_media: "{{ (smb_share_items | selectattr('name','equalto','media') | list | first | default({})) }}"
    smb_utatane: "{{ (smb_share_items | selectattr('name','equalto','utatane') | list | first | default({})) }}"

- name: Build desired SMB share objects
  set_fact:
    smb_media_desired:
      name: media
      comment: raspi-media-server
      sharedfolderref: "{{ media_sharedfolder_uuid }}"
      browseable: true
      readonly: true
      guest: 'no'
      extraoptions: "valid users = @users"
    smb_utatane_desired:
      name: utatane
      comment: raspi-media-server
      sharedfolderref: "{{ utatane_sharedfolder_uuid }}"
      browseable: true
      readonly: false
      guest: 'no'
      extraoptions: "valid users = {{ admin_account_name }}"

- name: Decide if media share needs update
  set_fact:
    smb_media_needs_update: >-
      {{
        (smb_media.get('sharedfolderref') | default('')) != smb_media_desired.sharedfolderref
        or (smb_media.get('readonly') | default(false) | bool) != (smb_media_desired.readonly | bool)
        or (smb_media.get('guest') | default('no')) != smb_media_desired.guest
        or (smb_media.get('extraoptions') | default('')) != smb_media_desired.extraoptions
      }}

- name: Decide if utatane share needs update
  set_fact:
    smb_utatane_needs_update: >-
      {{
        (smb_utatane.get('sharedfolderref') | default('')) != smb_utatane_desired.sharedfolderref
        or (smb_utatane.get('readonly') | default(false) | bool) != (smb_utatane_desired.readonly | bool)
        or (smb_utatane.get('guest') | default('no')) != smb_utatane_desired.guest
        or (smb_utatane.get('extraoptions') | default('')) != smb_utatane_desired.extraoptions
      }}

- name: Create/Update SMB share 'media'
  shell: >-
    omv-rpc 'Smb' 'setShare' '{{ smb_media_desired | to_json }}'
  register: smb_media_set
  changed_when: true
  when: smb_media_needs_update

- name: Create/Update SMB share 'utatane'
  shell: >-
    omv-rpc 'Smb' 'setShare' '{{ smb_utatane_desired | to_json }}'
  register: smb_utatane_set
  changed_when: true
  when:
    - utatane_sharedfolder_uuid | length > 0
    - smb_utatane_needs_update

