# vars_files:
  # - ../vault/all.yml

ansible_user: "yoiko" # raspiの管理ユーザー
set_hostname: "raspi-nas" # ホスト名
admin_authorized_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub').strip() }}"
dotenv_path: "" # raspi内のdotenvパス。空文字ならデフォルトで管理ユーザーのホームディレクトリに配置
timezone: "Asia/Tokyo"
target_uid: 1000
target_gid: 1000

install_omv: true

# UFWで開けるポート（OMV/SMB/NFS/SSHなど。環境に合わせて調整）
ufw_allow_ports:
  - "22"          # SSH
  - "80"          # HTTP (OMV WebUI)
  - "443"         # HTTPS (OMV WebUI)
  - "139"         # SMB
  - "445"         # SMB
  - "111"         # NFS rpcbind
  - "2049"        # NFS
  - "892"         # NFS mountd (環境で必要なら)
  - "873"         # rsync (必要なら)

dotenv:
  UID: "{{ target_uid }}"
  GID: "{{ target_gid }}"
  RASPI_TARGET_HOSTS: "{{ raspi_target_hosts }}"
  RASPI_SET_HOSTNAME: "{{ set_hostname }}"
  TZ: "{{ timezone }}"
  CONFIG_ROOT: /opt/docker
  CACHE_ROOT: /opt/docker/cache
  MEDIA_ROOT: /srv/dev-disk-by-uuid-XXXX/media
  VIDEOS_ROOT: /srv/dev-disk-by-uuid-XXXX/media/video
  PRIVATE_VIDEOS_ROOT: /srv/dev-disk-by-uuid-XXXX/utatane/video
  PICTURE_ROOT: /srv/dev-disk-by-uuid-XXXX/media/picture
  MANGA_PUBLIC_ROOT: /srv/dev-disk-by-uuid-XXXX/media/manga
  MANGA_PRIVATE_ROOT: /srv/dev-disk-by-uuid-XXXX/utatane/manga
  JELLYFIN_PUBLISHED_URL: ""
  KOMGA_JAVA_OPTS: "-Xms512m -Xmx1024m"
  TAILSCALE_AUTHKEY: ""
  TAILSCALE_HOSTNAME: raspi-media
  TAILSCALE_EXTRA_ARGS: ""
