# vars_files:
  # - ../vault/all.yml

ansible_user: "yoiko" # raspiの管理ユーザー
set_hostname: "raspi-nas" # ホスト名
admin_authorized_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub').strip() }}"
dotenv_path: "" # raspi内のdotenvパス。空文字ならデフォルトで管理ユーザーのホームディレクトリに配置
timezone: "Asia/Tokyo"
target_uid: 1000
target_gid: 1000

# OMV がマウントするデバイスの UUID（`/srv/dev-disk-by-uuid-<UUID>`）
storage_uuid: "6a6025aa-94a1-4552-a1ee-676db616b634"
# UUID から導出されるマウントルート。UUID 未設定時はプレースホルダ `XXXX` を使う。
storage_mount_root: "/srv/dev-disk-by-uuid-{{ storage_uuid | default('XXXX', true) }}"

install_omv: true

# UFWで開けるポート（OMV/SMB/NFS/SSHなど。環境に合わせて調整）
ufw_allow_ports:
  - "22"          # SSH
  - "80"          # HTTP (OMV WebUI)
  - "443"         # HTTPS (OMV WebUI)
  - "139"         # SMB
  - "445"         # SMB
  - "111"         # NFS rpcbind
  - "2049"        # NFS
  - "892"         # NFS mountd (環境で必要なら)
  - "873"         # rsync (必要なら)

dotenv:
  UID: "{{ target_uid }}"
  GID: "{{ target_gid }}"
  RASPI_TARGET_HOSTS: "{{ raspi_target_hosts }}"
  RASPI_SET_HOSTNAME: "{{ set_hostname }}"
  TZ: "{{ timezone }}"
  CONFIG_ROOT: /opt/docker
  CACHE_ROOT: /opt/docker/cache
  MEDIA_ROOT: "{{ storage_mount_root }}/media"
  VIDEOS_ROOT: "{{ storage_mount_root }}/media/video"
  PRIVATE_VIDEOS_ROOT: "{{ storage_mount_root }}/utatane/video"
  PICTURE_ROOT: "{{ storage_mount_root }}/media/picture"
  PRIVATE_PICTURE_ROOT: "{{ storage_mount_root }}/utatane/picture"
  MANGA_PUBLIC_ROOT: "{{ storage_mount_root }}/media/manga"
  MANGA_PRIVATE_ROOT: "{{ storage_mount_root }}/utatane/manga"
  JELLYFIN_PUBLISHED_URL: ""
  KOMGA_JAVA_OPTS: "-Xms512m -Xmx1024m"
  TAILSCALE_AUTHKEY: ""
  TAILSCALE_HOSTNAME: raspi-media
  TAILSCALE_EXTRA_ARGS: ""

# Services initial config
services_jellyfin:
  enable: true
  admin_user: ""         # 初回セットアップ用。未設定ならスキップ
  admin_password: ""     # 初回セットアップ用。未設定ならスキップ
  libraries: []           # 例: [{ name: Videos, path: /media/video, collection_type: movies }]

services_komga:
  enable: true
  admin_email: ""        # 初回クレーム/BasicAuth 用
  admin_password: ""     # 初回クレーム/BasicAuth 用
  public_library_name: "Manga Public"
  private_library_name: "Manga Private"
  create_private_library: false

# OMV (SMB) 設定の既定値
omv_smb:
  enable: true
  workgroup: WORKGROUP
  min_protocol: SMB2
  max_protocol: SMB3
  ntlm: false
  recycle: true
