---
- name: Set UFW default deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set UFW default allow outgoing
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: UFW allow needed ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ufw_allow_ports }}"

- name: Ensure UFW enabled
  community.general.ufw:
    state: enabled
