---
# Raspberry Pi セットアップのエントリーポイント
# 仕様変更: OMV インストール後に IP が変わり SSH 切断が発生するため、
# 前提としてraspi_bootstrapを実行しomvをインストール後、IPアドレスを調整する。その後、以下を順に実行:
- import_playbook: raspi_post_omv.yml
- import_playbook: omv_storage.yml
- import_playbook: omv_config.yml
# - import_playbook: services_config.yml
