---
- name: Raspberry Pi 事後設定 (OMV 導入後)
  hosts: raspi
  gather_facts: yes
  become: yes

  vars_files:
    - ../vault/all.yml

  pre_tasks:
    - name: OMV が導入済みか確認する
      stat:
        path: /etc/openmediavault/config.xml
      register: omv_config

    - name: OMV 未導入時は中断する
      fail:
        msg: "OMV が見つかりません。先に raspi_bootstrap.yml を完了してください。"
      when: not omv_config.stat.exists

    - import_tasks: tasks/pre_common.yml

  tasks:
    - import_role:
        name: admin_account

    - import_role:
        name: personal_user

    - name: Recompute dotenv path after admin_account
      set_fact:
        dotenv_path: "{{ dotenv_path | default(admin_account_home + '/raspi-media-server/.env', true) }}"
      tags: ['dotenv']

    - import_role:
        name: dotenv

    - import_role:
        name: omv_extras
