---
- name: Ensure admin .ssh directory exists
  file:
    path: "{{ admin_user_home }}/.ssh"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
  when: admin_user_home is defined and (admin_user_home | length) > 0

- name: Install admin authorized key
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ admin_authorized_key }}"
    state: present
