---
- name: OpenMediaVault 設定適用
  hosts: "{{ lookup('env', 'RASPI_TARGET_HOSTS') }}"
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Validate required environment for hosts
      assert:
        that:
          - (lookup('env','RASPI_TARGET_HOSTS') | length) > 0
        fail_msg: |
          必須変数が不足しています。以下を環境変数で設定してください:
            - RASPI_TARGET_HOSTS (インベントリのホスト/グループ名)

    - name: Check OpenMediaVault presence
      stat:
        path: /etc/openmediavault/config.xml
      register: omv_config

    - name: Abort when OMV is not installed yet
      fail:
        msg: "OMV が見つかりません。先に raspi_bootstrap.yml を完了してください。"
      when: not omv_config.stat.exists

  tasks:
    - name: Placeholder for OMV configuration tasks
      debug:
        msg: "OMV 設定タスクをここに追加してください。"
      tags: ['always']
