---
# OMV 管理下のマウント配下に、README 記載のディレクトリ案を作成する。
# 前提: プレイブック側で dotenv を読み込み、mount_root の存在を検証済み。

- name: Derive storage layout paths
  set_fact:
    media_root: "{{ dotenv.MEDIA_ROOT | default('') }}"
    videos_root: "{{ dotenv.VIDEOS_ROOT | default('') }}"
    picture_root: "{{ dotenv.PICTURE_ROOT | default('') }}"
    manga_public_root: "{{ dotenv.MANGA_PUBLIC_ROOT | default('') }}"
    utatane_root: "{{ dotenv.UTATANE_ROOT | default('') }}"
    private_videos_root: "{{ dotenv.PRIVATE_VIDEOS_ROOT | default('') }}"
    private_picture_root: "{{ dotenv.PRIVATE_PICTURE_ROOT | default('') }}"
    manga_private_root: "{{ dotenv.MANGA_PRIVATE_ROOT | default('') }}"

- name: Compute Jellyfin subdirectories (movies, tvshows)
  set_fact:
    movies_dir: "{{ videos_root + '/movies' if (videos_root | length > 0) else '' }}"
    tvshows_dir: "{{ videos_root + '/tvshows' if (videos_root | length > 0) else '' }}"

- name: Build directory list from dotenv and README layout
  set_fact:
    omv_storage_dirs: >-
      {{
        [media_root, videos_root, movies_dir, tvshows_dir, picture_root, manga_public_root,
         utatane_root, private_videos_root, private_picture_root, manga_private_root]
        | select('defined')
        | select('string')
        | reject('equalto', '')
        | list
      }}

- name: Ensure storage directories exist (under OMV mount)
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ omv_storage_owner | default(ansible_user) }}"
    group: "{{ omv_storage_group | default(ansible_user) }}"
    mode: "{{ omv_storage_dir_mode | default('0755') }}"
  loop: "{{ omv_storage_dirs }}"
  when:
    - item is defined
    - item | string | length > 0
    - item.startswith(mount_root + '/') or (item == mount_root) or item.startswith(media_root + '/') or (item == media_root)

- name: Set utatane group ownership for private directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ omv_storage_owner | default(ansible_user) }}"
    group: "{{ utatane_group.name | default('utatane') }}"
    mode: "0770"  # グループメンバーのみアクセス可能
  loop:
    - "{{ utatane_root }}"
    - "{{ private_videos_root }}"
    - "{{ private_picture_root }}"
    - "{{ manga_private_root }}"
  when:
    - item is defined
    - item | string | length > 0
    - utatane_root is defined
    - utatane_root | length > 0
