---
- name: Install OpenMediaVault when requested
  when: install_omv | bool
  block:
    - name: Check if OMV already provisioned
      stat:
        path: /etc/openmediavault/config.xml
      register: omv_config

    - name: Download OMV installer script
      get_url:
        url: https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install
        dest: /root/omv_install.sh
        mode: '0755'
      when: not omv_config.stat.exists

    - name: Run OMV installer without automatic reboot
      shell: OMV_INSTALLER_SKIP_REBOOT=yes /root/omv_install.sh
      args:
        creates: /etc/openmediavault/config.xml
      register: omv_install
      when: not omv_config.stat.exists

    - name: Reboot if OMV just installed
      reboot:
        reboot_timeout: 600
        test_command: /bin/true
      when:
        - omv_install_reboot | bool
        - (omv_install is defined and omv_install is changed)
