---
- name: Install OpenMediaVault when requested
  when: install_omv | bool
  block:
    - name: Check if OMV already provisioned
      stat:
        path: /etc/openmediavault/config.xml
      register: omv_config

    - name: Download OMV installer script
      get_url:
        url: https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install
        dest: /root/omv_install.sh
        mode: '0755'
      when: not omv_config.stat.exists

    - name: Run OMV installer without automatic reboot
      shell: OMV_INSTALLER_SKIP_REBOOT=yes /root/omv_install.sh
      args:
        creates: /etc/openmediavault/config.xml
      register: omv_install
      when: not omv_config.stat.exists

    - name: Ensure omv-extras package installed
      apt:
        name: openmediavault-omvextrasorg
        state: present
        update_cache: yes
      register: omv_extras_install
      when: omv_config.stat.exists or (omv_install is defined and not (omv_install is skipped))

    - name: Reboot if OMV or omv-extras just installed
      reboot:
        reboot_timeout: 600
        test_command: /bin/true
      when:
        - (omv_install is defined and omv_install is changed) or
          (omv_extras_install is defined and omv_extras_install is changed)
